### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:3306 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)

### ISSUE THREAD

**Issue by diogocsc** [diogocsc/inbetween#4]
Cannot connect to mysql database... why?
I've altered firewall to give inbound access to port 3306.

Here is the error message when calling `node mysql_boot.js` from the console and experimented changing host to 127.0.0.1, with same issue.

```
F:\Projetos\Papo A Papo\in between>node mysql_boot.js
Could not establish a connection to the database
F:\Projetos\Papo A Papo\in between\mysql_boot.js:53
        throw error;
        ^

Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
    --------------------
    at Protocol._enqueue (F:\Projetos\Papo A Papo\in between\node_modul
lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (F:\Projetos\Papo A Papo\in between\node_modu
\lib\protocol\Protocol.js:51:23)
    at Connection.connect (F:\Projetos\Papo A Papo\in between\node_modu
\lib\Connection.js:119:18)
    at Object.<anonymous> (F:\Projetos\Papo A Papo\in between\mysql_boo
2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:70
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
```

**Comment by diogocsc** [comment]
MySql Server was not installed. After installing it this issue was overcome.

**Comment by diogocsc** [comment]
MySql Server was not installed. After installing it this issue was overcome.

**Comment by akedevs** [comment]
diogocsc : incorrect for your anwer

**Comment by zakyymuh** [comment]
instead of using localhost, replace "localhost" to  "::1"  and it works fine to me.
